# kubernetes/backstage.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: devops-tools
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: herbergt/sip-developer-portal:1.0.0-5146931
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "1024m"
          envFrom:
            - secretRef:
                name: backstage-secrets
  image:
    template:
      spec:
        containers:
          - image: herbergt/sip-developer-portal:$IMAGE_TAG
