on:
  push:
    branches:
      - main
    paths-ignore:
      - '.hc-k8s/**'
      - '.github/**'
      - 'config/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: release-please-action
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: root
